#!/usr/bin/env bash
# Cloud Agent install for ecd-assessment. Idempotent: safe to re-run.
set -euo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

# --- Node 24 (pinned by .node-version) via nvm -------------------------------
# The runtime prepends its own node to PATH, so pin the app's node explicitly
# through nvm rather than relying on the default `node` on PATH.
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
if [ ! -s "$NVM_DIR/nvm.sh" ]; then
  mkdir -p "$NVM_DIR"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
fi
# shellcheck disable=SC1091
. "$NVM_DIR/nvm.sh"
NODE_VERSION="$(tr -d '[:space:]' < .node-version)"   # e.g. v24.19.0
nvm install "$NODE_VERSION"
nvm use "$NODE_VERSION"
node -v

# --- Dependencies ------------------------------------------------------------
npm ci

# --- Local dev .env (gitignored) ---------------------------------------------
# JSON flat-file store means no external MongoDB is needed for local dev.
if [ ! -f .env ]; then
  JWT_SECRET="$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")"
  cat > .env <<EOF
# Generated by .cursor/install.sh for local Cloud Agent dev. Gitignored.
VITE_AUTH_URL=/api/users/login
JWT_SECRET=${JWT_SECRET}
TOKEN_EXPIRES_IN=8h
DB_MODE=json
ECD_DB_FILE=./data/db.json
ECD_BACKUP_DIR=./data/backups
EOF
  echo "Wrote .env with a generated JWT_SECRET."
fi

# --- Seed the JSON store with the four dev accounts --------------------------
# Hashes come straight from server/users.json (admin1/dist1/teach1/stud1 with
# passwords admin123/dist123/teach123/stud123). Only seeds a fresh store.
mkdir -p data
if [ ! -f data/db.json ]; then
  node -e '
    const fs = require("fs");
    const seed = require("./server/users.json");
    const emails = { admin1:"admin@ecd.local", dist1:"district@ecd.local", teach1:"teacher@ecd.local", stud1:"student@ecd.local" };
    const users = seed.map(u => ({ id:u.username, username:u.username, password:u.password, role:u.role, email:emails[u.username]||"", profile:{} }));
    fs.writeFileSync("./data/db.json", JSON.stringify({ users }, null, 2));
    console.log("Seeded data/db.json with users:", users.map(u => u.username).join(", "));
  '
fi

echo "install.sh complete."
